language: c
compiler:
  - gcc
  - clang
before_install:
  # OpenGL Extension Wrangler
  - sudo apt-get install -y libglew-dev
script:
  - (mkdir build && cd build && cmake -DBUILD_TESTS=ON .. -G "Unix Makefiles" && make)
  - build/runTests