language: c
compiler:
  - gcc
  - clang
before_install:
  # OpenGL Extension Wrangler & Google Test
  - sudo apt-get install -y libglew-dev libgtest-dev
  # GTest (copying libgtest.a and libgtest_main.a to /usr/lib)
  - (cd /usr/src/gtest && sudo cmake . && sudo make && sudo cp *.a /usr/lib)
script:
  - (mkdir build && cd build && cmake -DBUILD_TESTS=ON .. -G "Unix Makefiles" && make)
  - build/runTests