language: c
compiler:
  - gcc
  - clang
before_install:
  # OpenGL Extension Wrangler & Google Test & lcov
  - sudo apt-get install -y libglew-dev libgtest-dev lcov
  # GTest (copying libgtest.a and libgtest_main.a to /usr/lib) & Coveralls::Lcov
  - (cd /usr/src/gtest && sudo cmake . && sudo make && sudo cp *.a /usr/lib)
  - gem install coveralls-lcov
script:
  - (mkdir build && cd build && cmake -DBUILD_TESTS=ON .. -G "Unix Makefiles" && make)
after_success:
  # - lcov --directory . --capture --output-file coverage.info --no-external && coveralls-lcov --source-encoding=ISO-8859-1 coverage.info
  # create baseline coverage data file
  - lcov -c -i -d . -o app_base.info
  # perform test
  - build/runTests
  # create test coverage data file, combine baseline and test coverage data and remove output for external libraries
  - lcov -c -d . -o app_test.info && lcov -a app_base.info -a app_test.info -o app_all.info && lcov --extract app_all.info "$PWD/include/*" -o coverage.info
  - coveralls-lcov --source-encoding=ISO-8859-1 coverage.info
