language: c
compiler:
  - gcc
before_install:
  - curl -O https://www.libsdl.org/release/SDL2-2.0.3.tar.gz
  - tar -xzvf SDL2-2.0.3.tar.gz
  - (cd SDL2-2.0.3 && ./configure && make && sudo make install)
  - sudo apt-get install -y libglew-dev
  - sudo apt-get install -y libsoil-dev
  - sudo apt-get install -y libassimp-dev
  - sudo apt-get install -y libbullet-dev
script: mkdir build && cd build && cmake .. -G "Unix Makefiles" && make && ./game
