language: c
compiler:
  - gcc
  - clang
before_install:
  # SDL2
  - curl -O https://www.libsdl.org/release/SDL2-2.0.3.tar.gz
  - tar -xzvf SDL2-2.0.3.tar.gz
  - (cd SDL2-2.0.3 && ./configure && make && sudo make install)
  # OpenGL Extension Wrangler
  - sudo apt-get install -y libglew-dev
  # Simple OpenGL Image Library
  - sudo apt-get install -y libsoil-dev
  # Assimp
  - wget -N https://github.com/assimp/assimp/archive/master.zip
  - unzip master.zip
  - (cd assimp-master && cmake -DASSIMP_BUILD_ASSIMP_TOOLS=OFF -DASSIMP_BUILD_SAMPLES=OFF -DASSIMP_BUILD_TESTS=OFF . -G "Unix Makefiles" && make && sudo make install)
  # Bullet Physics
  - wget -N https://github.com/bulletphysics/bullet3/archive/master.zip
  - unzip master.zip
  - (cd bullet3-master && cmake -DBUILD_BULLET2_DEMOS=OFF -DBUILD_OPENGL3_DEMOS=OFF -DBUILD_EXTRAS=OFF -DBUILD_UNIT_TESTS=OFF . -G "Unix Makefiles" && make && sudo make install)
  - sudo pip install cpp-coveralls
script:
  - mkdir build && cd build && cmake -DBUILD_UNIT_TESTS=ON .. -G "Unix Makefiles" && make
  - make test
  - ctest
  - ctest ..
  - ctest ../test
after_success:
  - coveralls --include include --include src --gcov-options '\-lp'

