language: c
compiler:
  - gcc
before_install:
  - sudo add-apt-repository -y ppa:zoogie/sdl2-snapshots
  - sudo apt-get install -y libsdl2-dev
  - sudo apt-get install -y libglew-dev
  - sudo apt-get install -y libsoil-dev
  - sudo apt-get install -y libassimp-dev
  - sudo apt-get install -y libbullet-dev
script: mkdir build && cd build && cmake .. -G "Unix Makefiles" && make && ./game
