language: c
compiler:
  - gcc
  - clang
before_install:
  # OpenGL Extension Wrangler & Simple OpenGL Image Library & Google Test & lcov
  - sudo apt-get install -y libglew-dev libsoil-dev libgtest-dev lcov
  # SDL2
  - curl -O https://www.libsdl.org/release/SDL2-2.0.3.tar.gz
  - tar -xzvf SDL2-2.0.3.tar.gz
  - (cd SDL2-2.0.3 && ./configure && make && sudo make install)
  # Assimp
  - wget -N https://github.com/assimp/assimp/archive/master.zip
  - unzip master.zip
  - (cd assimp-master && cmake -DASSIMP_BUILD_ASSIMP_TOOLS=OFF -DASSIMP_BUILD_SAMPLES=OFF -DASSIMP_BUILD_TESTS=OFF . -G "Unix Makefiles" && make && sudo make install)
  # Bullet Physics
  - wget -N https://github.com/bulletphysics/bullet3/archive/master.zip
  - unzip master.zip
  - (cd bullet3-master && cmake -DBUILD_BULLET2_DEMOS=OFF -DBUILD_OPENGL3_DEMOS=OFF -DBUILD_EXTRAS=OFF -DBUILD_UNIT_TESTS=OFF . -G "Unix Makefiles" && make && sudo make install)
  # GTest (copying libgtest.a and libgtest_main.a to /usr/lib) & Coveralls::Lcov
  - (cd /usr/src/gtest && sudo cmake . && sudo make && sudo cp *.a /usr/lib)
  - gem install coveralls-lcov
  # Protobuf
  - wget https://github.com/google/protobuf/releases/download/v3.0.0-alpha-1/protobuf-cpp-3.0.0-alpha-1.tar.gz
  - tar -xzvf protobuf-cpp-3.0.0-alpha-1.tar.gz
  - (cd protobuf-3.0.0-alpha-1 && ./configure --prefix=/usr && make && sudo make install)
script:
  - (mkdir build && cd build && cmake -DBUILD_TESTS=ON .. -G "Unix Makefiles" && make)
after_success:
  # - lcov --directory . --capture --output-file coverage.info --no-external && coveralls-lcov --source-encoding=ISO-8859-1 coverage.info
  # create baseline coverage data file
  - lcov -c -i -d . -o app_base.info
  # perform test
  - build/runTests
  # create test coverage data file, combine baseline and test coverage data and remove output for external libraries
  - lcov -c -d . -o app_test.info && lcov -a app_base.info -a app_test.info -o app_all.info && lcov --extract app_all.info "$PWD/include/*" -o coverage.info
  - coveralls-lcov --source-encoding=ISO-8859-1 coverage.info
