language: c
compiler:
  - gcc
  - clang
before_install:
  # OpenGL Extension Wrangler & Google Test & lcov
  - sudo apt-get install -y libglew-dev libgtest-dev lcov
  # GTest (copying libgtest.a and libgtest_main.a to /usr/lib) & Coveralls::Lcov
  - (cd /usr/src/gtest && sudo cmake . && sudo make && sudo cp *.a /usr/lib)
  - gem install coveralls-lcov
  - lcov --version
  - lcov --directory . --zerocounters # init coverage to 0
script:
  - (mkdir build && cd build && cmake -DBUILD_TESTS=ON .. -G "Unix Makefiles" && make)
  - build/runTests
after_success:
  - lcov --directory . --capture --output-file coverage.info # capture
  - lcov --remove coverage.info 'test/*' '/usr/*' --output-file coverage.info # filter out system and test code
  - lcov --list coverage.info # debug before upload
  - coveralls-lcov --source-encoding=ISO-8859-1 coverage.info # upload to coveralls
